update working-with-github/Readme
kysect/Main pull request #22
Opened 2021-06-10 13:16 UTC by ALEXXXANDRO

Добавил информацию о репозиториях, ветках, коммитах.  Добавил немного информации о VS и Intellij

2021-06-10 19:13 UTC, Bibletoon requested changes

2021-06-10 19:13 UTC, Bibletoon commented on articles/working-with-github/README.md
> +Итак, по какой либо причине вы отказались от удобного UI и решили пользоваться встроенными средствами Visual Studio.
```suggestion
Итак, по какой-либо причине вы отказались от удобного UI и решили пользоваться встроенными средствами Visual Studio.
```

2021-06-10 19:13 UTC, Bibletoon commented on articles/working-with-github/README.md
> +Вы работали над проектом и в какой то момент решили добавить git репозиторий? Нет проблем - жмите на эту кнопку (да у автора русская Visual Studio, и да, однажды, он это исправит)
```suggestion
Вы работали над проектом и в какой-то момент решили добавить git репозиторий? Нет проблем - жмите на эту кнопку (да, у автора русская Visual Studio, и да, однажды он это исправит)
```

2021-06-10 19:13 UTC, Bibletoon commented on articles/working-with-github/README.md
> +После клика на "фиксация"\"commit" открывается следующее окошко. В нём мы и создаем наш коммит, после чего его можно запушить, нажав на соответствующую кнопку.
```suggestion
После клика на "фиксация"/"commit" открывается следующее окошко. В нём мы и создаем наш коммит, после чего его можно запушить, нажав на соответствующую кнопку.
```

2021-06-10 19:13 UTC, Bibletoon commented on articles/working-with-github/README.md
> +Кроме того, Intellij idea предоставляет относительно удобную работу с ветками, если вы по каким то причинам не хотите устанавливать Gitkraken. После клика на Branches во вкладке Git перед нами появит
```suggestion
Кроме того, Intellij idea предоставляет относительно удобную работу с ветками, если вы по каким то причинам не хотите устанавливать Gitkraken. После клика на Branches во вкладке Git, перед нами появится следующее окошко, в котором мы можем создавать новые ветки (New branch), переходить между ветками (Checkout branch) и делать прочие непотребства
```

2021-06-10 19:13 UTC, Bibletoon commented on articles/working-with-github/README.md
> +### Intellij idea
Возможно стоит написать в заголовке "IDE от JetBrains" и где-то в первом предложении сказать, что во всех них система работы с гитом аналогичная, а мы рассмотрим её на примере Rider (Когда в тексте идёт Intellij idea, а на скриншотах Rider, есть какое-то неприятное чувство диссонанса)

2021-06-10 19:32 UTC, annchous commented on articles/working-with-github/README.md
> +И вдруг, в какой то момент, вы понимаете, что ваша фича не работает и всё очень плохо, и лучше бы вернуть всё как было... Но вот незадача - помимо ваших изменений откатятся и изменения других людей,
```suggestion
И вдруг в какой-то момент вы понимаете, что ваша фича не работает, и всё очень плохо, и лучше бы вернуть всё, как было... Но вот незадача: помимо ваших изменений откатятся и изменения других людей, а там всё было хорошо.
```

2021-06-10 19:32 UTC, annchous commented on articles/working-with-github/README.md
> +И вдруг, в какой то момент, вы понимаете, что ваша фича не работает и всё очень плохо, и лучше бы вернуть всё как было... Но вот незадача - помимо ваших изменений откатятся и изменения других людей,
Наверно так

2021-06-10 19:41 UTC, annchous commented on articles/working-with-github/README.md
> +Сам репозиторий представляет собой каталог файловой системы, в котором хранится ваш проект и вещи, необходимые ему для корректной работы. Репозитории бывают локальными (лежит у нас на компе) и удалён
GIthub

2021-06-10 19:42 UTC, annchous commented on articles/working-with-github/README.md
> +Также, на Github есть деление на private и public репозитории. Public репозитории доступны всем желающим, а Private только вам, и тем, кому вы предоставите эту возможность.
```suggestion
Также на Github есть деление на private и public репозитории. Public репозитории доступны всем желающим, а Private только вам и тем, кому вы предоставите эту возможность.
```

2021-06-10 19:42 UTC, annchous commented on articles/working-with-github/README.md
> +Если вы хотите добавить кого то в приватный репозиторий, вам поможет вкладка manage access
```suggestion
Если вы хотите добавить кого-то в приватный репозиторий, вам поможет вкладка manage access
```

2021-06-10 19:45 UTC, annchous commented on articles/working-with-github/README.md
> +Также, по клику на вкладку Git в правом нижнем углу экрана (она появится только если у вас уже есть Git репозиторий), можно открыть окошко с отрисовкой веток, и возможностью перемещения по коммитам.
```suggestion
Также по клику на вкладку Git в правом нижнем углу экрана (она появится только если у вас уже есть Git репозиторий) можно открыть окошко с отрисовкой веток и возможностью перемещения по коммитам.
```

2021-06-12 07:47 UTC, FrediKats commented
@ALEXXXANDRO any updates?

2021-06-14 09:45 UTC, ALEXXXANDRO commented
@FrediKats думаю готово

2021-06-14 11:33 UTC, FrediKats commented
@ALEXXXANDRO это скорее был пинг, что там есть что пофиксить еще нужно) Я померджил саджесты, оставил пару правок на которые нужно обратить внимание.

2021-06-27 10:44 UTC, ALEXXXANDRO commented on articles/working-with-github/README.md
> +### Intellij idea
done

2021-06-27 10:51 UTC, ALEXXXANDRO commented on articles/working-with-github/README.md
> +Про подробное устройство репозитория и то, как он работает внутри можно почитать тут https://www.google.ru
done

2021-06-27 10:52 UTC, ALEXXXANDRO commented
@FrediKats  я помёрджил оставшееся и добавил пару ссылок. Думаю можно закрывать пр?

2021-06-27 11:02 UTC, FrediKats approved these changes

2021-06-27 11:02 UTC, merged