Рефакторинг тестового
kysect/Main pull request #34
Opened 2022-06-06 16:21 UTC by s4xack

Избавился от акцента на тексте комманд и постарался выделить требуемый фукнционал.

2022-06-07 02:00 UTC, FrediKats requested changes
Мне кажется, что таки не хватает какой-то доп информации о том, что подразумевается под консольным интерфейсом, как его делать и как он в итоге должен получиться.

+ можно про импорт и экспорт чуть подробнее написать и может с примерами. Люди редко доходили до JSON, обычно это самописный формат в .txt.

Нужны ли какие-то статьи и референсы?

123

2022-06-14 12:29 UTC, s4xack commented
Ну я докинул.
Не очень понимаю, на что вообще можно дать референсы, метанит?) Кажется всякими референсами можно только запутать.

2022-06-18 04:23 UTC, FrediKats commented
Мне в целом ок.
@Bibletoon @annchous ?

2022-06-18 05:53 UTC, Bibletoon approved these changes

2022-06-23 04:56 UTC, merged